apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: northamerica-south1-docker.pkg.dev/verdant-legacy-445203-c0/notifications/production
          name: notifications
          env:
            - name: SMTP_USER
              value: kaiquekapo.govani@gmail.com
            - name: TCP_PORT
              value: '3004'
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: 846494886941-40gjginbhditgte6buuqpmpa042bsgvd.apps.googleusercontent.com
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientSecret
            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google
                  key: refreshToken
          ports:
            - containerPort: 3004
