steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-south1-docker.pkg.dev/verdant-legacy-445203-c0/reservations/production',
        '-f',
        './apps/reservations/Dockerfile',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-south1-docker.pkg.dev/verdant-legacy-445203-c0/reservations/production',
      ]

  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-south1-docker.pkg.dev/verdant-legacy-445203-c0/auth/production',
        '-f',
        './apps/auth/Dockerfile',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-south1-docker.pkg.dev/verdant-legacy-445203-c0/auth/production',
      ]

  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-south1-docker.pkg.dev/verdant-legacy-445203-c0/notifications/production',
        '-f',
        './apps/notifications/Dockerfile',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-south1-docker.pkg.dev/verdant-legacy-445203-c0/notifications/production',
      ]

  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'northamerica-south1-docker.pkg.dev/verdant-legacy-445203-c0/payments/production',
        '-f',
        './apps/payments/Dockerfile',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'northamerica-south1-docker.pkg.dev/verdant-legacy-445203-c0/payments/production',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
