services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    restart: always

  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    command: npm run dev reservations

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    command: npm run dev auth

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    command: npm run dev payments

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    command: npm run dev notifications
