FROM node:20-alpine AS development

WORKDIR /usr/src/app

COPY package*.json tsconfig.json nest-cli.json ./

COPY apps/auth apps/auth
COPY libs libs

RUN npm install
RUN npm run build auth

FROM node:20-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./
COPY apps/auth/package*.json ./apps/auth/

RUN npm install --omit=dev

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/apps/auth/main"]